# Generated by Django 5.0.2 on 2024-03-02 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('idalergia', models.AutoField(db_column='idAlergia', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'alergia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('idasistente', models.AutoField(db_column='idAsistente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('escolaridad', models.CharField(blank=True, max_length=45, null=True)),
                ('salario', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asistente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idcita', models.AutoField(db_column='idCita', primary_key=True, serialize=False)),
                ('fecha_propuesta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cita',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('idmaterial', models.AutoField(db_column='idMaterial', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('serie_modelo', models.CharField(blank=True, max_length=45, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio_individual', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'material',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoEspecialidad',
            fields=[
                ('idtipo_especialidad', models.AutoField(db_column='idTipo_Especialidad', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipo_especialidad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idtipo_usuario', models.AutoField(db_column='idTipo_Usuario', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('permisos', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('idtratamientno', models.AutoField(db_column='idTratamientno', primary_key=True, serialize=False)),
                ('detalle', models.CharField(blank=True, max_length=45, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('cantidad_citas', models.IntegerField(blank=True, null=True)),
                ('asistente_idasistente', models.ForeignKey(db_column='Asistente_idAsistente', on_delete=django.db.models.deletion.DO_NOTHING, to='app.asistente')),
                ('cita_idcita', models.ForeignKey(db_column='Cita_idCita', on_delete=django.db.models.deletion.DO_NOTHING, to='app.cita')),
            ],
            options={
                'db_table': 'tratamiento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idpaciente', models.AutoField(db_column='idPaciente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('numero_telefonico', models.CharField(blank=True, max_length=45, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('numero_seguro', models.CharField(blank=True, max_length=45, null=True)),
                ('cita_idcita', models.ForeignKey(db_column='Cita_idCita', on_delete=django.db.models.deletion.DO_NOTHING, to='app.cita')),
            ],
            options={
                'db_table': 'paciente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('iddentista', models.AutoField(db_column='idDentista', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=45, null=True)),
                ('no_colegiado', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo_especialidad_idtipo_especialidad', models.ForeignKey(db_column='Tipo_Especialidad_idTipo_Especialidad', on_delete=django.db.models.deletion.DO_NOTHING, to='app.tipoespecialidad')),
            ],
            options={
                'db_table': 'dentista',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idfactura', models.AutoField(db_column='idFactura', primary_key=True, serialize=False)),
                ('detalle', models.CharField(blank=True, max_length=45, null=True)),
                ('cantidad_servicios', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('tratamiento_idtratamientno', models.ForeignKey(db_column='Tratamiento_idTratamientno', on_delete=django.db.models.deletion.DO_NOTHING, to='app.tratamiento')),
            ],
            options={
                'db_table': 'factura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=45)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('asistente_idasistente', models.ForeignKey(db_column='Asistente_idAsistente', on_delete=django.db.models.deletion.DO_NOTHING, to='app.asistente')),
                ('dentista_iddentista', models.ForeignKey(db_column='Dentista_idDentista', on_delete=django.db.models.deletion.DO_NOTHING, to='app.dentista')),
                ('tipo_usuario_idtipo_usuario', models.ForeignKey(db_column='Tipo_Usuario_idTipo_Usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='app.tipousuario')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AlergiaPaciente',
            fields=[
                ('alergia_idalergia', models.OneToOneField(db_column='Alergia_idAlergia', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.alergia')),
                ('paciente_idpaciente', models.ForeignKey(db_column='Paciente_idPaciente', on_delete=django.db.models.deletion.DO_NOTHING, to='app.paciente')),
            ],
            options={
                'db_table': 'alergia_paciente',
                'managed': True,
                'unique_together': {('alergia_idalergia', 'paciente_idpaciente')},
            },
        ),
        migrations.CreateModel(
            name='DentistaTratamiento',
            fields=[
                ('dentista_iddentista', models.OneToOneField(db_column='Dentista_idDentista', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.dentista')),
                ('tratamiento_idtratamientno', models.ForeignKey(db_column='Tratamiento_idTratamientno', on_delete=django.db.models.deletion.DO_NOTHING, to='app.tratamiento')),
            ],
            options={
                'db_table': 'dentista_tratamiento',
                'managed': True,
                'unique_together': {('dentista_iddentista', 'tratamiento_idtratamientno')},
            },
        ),
        migrations.CreateModel(
            name='TratamientoMaterial',
            fields=[
                ('tratamiento_idtratamientno', models.OneToOneField(db_column='Tratamiento_idTratamientno', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.tratamiento')),
                ('cantidad_utilizada', models.IntegerField(blank=True, null=True)),
                ('material_idmaterial', models.ForeignKey(db_column='Material_idMaterial', on_delete=django.db.models.deletion.DO_NOTHING, to='app.material')),
            ],
            options={
                'db_table': 'tratamiento_material',
                'managed': True,
                'unique_together': {('tratamiento_idtratamientno', 'material_idmaterial')},
            },
        ),
    ]
