# Generated by Django 5.0.2 on 2024-03-12 01:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='paciente_idpaciente',
            field=models.ForeignKey(db_column='paciente_idPaciente', default=6, on_delete=django.db.models.deletion.DO_NOTHING, to='app.paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
