-- MySQL Script generated by MySQL Workbench
-- Wed Jan 31 13:17:28 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clinica_dental
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `clinica_dental` ;

-- -----------------------------------------------------
-- Schema clinica_dental
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinica_dental` DEFAULT CHARACTER SET utf8 ;
USE `clinica_dental` ;

-- -----------------------------------------------------
-- Table `clinica_dental`.`Dentista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_dental`.`Dentista` (
  `idDentista` INT NOT NULL AUTO_INCREMENT,
  `nombre_completo` VARCHAR(45) NOT NULL,
  `numero_telefono` VARCHAR(45) NULL,
  `especialidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idDentista`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `clinica_dental`.`Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_dental`.`Material` (
  `idMaterial` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `serie/modelo` VARCHAR(45) NULL,
  `cantidad` INT NOT NULL,
  `precio_individual` DOUBLE NOT NULL,
  `precio_total` DOUBLE NULL,
  PRIMARY KEY (`idMaterial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_dental`.`Material_Tratamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_dental`.`Tratamiento` (
  `idTratamiento` INT NOT NULL AUTO_INCREMENT,
  `detalle` VARCHAR(45) NOT NULL,
  `cantidad_citas` INT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `idDentista` INT, -- Asumiendo que esta columna debe referenciar al dentista
  PRIMARY KEY (`idTratamiento`),
  CONSTRAINT `fk_dentista_id`
    FOREIGN KEY (`idDentista`)
    REFERENCES `clinica_dental`.`Dentista` (`idDentista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `clinica_dental`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_dental`.`Paciente` (
  `idPaciente` INT NOT NULL AUTO_INCREMENT,
  `nombre_completo` VARCHAR(45) NOT NULL,
  `edad` INT NULL,
  `alergias` VARCHAR(45) NOT NULL,
  `numero_telefono` VARCHAR(45) NULL,
  `numero_seguro` VARCHAR(45) NULL,
  PRIMARY KEY (`idPaciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_dental`.`Paciente_Tratamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_dental`.`Paciente_Tratamiento` (
  `fk_tratamiento_id` INT NOT NULL,
  `fk_paciente_id` INT NOT NULL,
  `cantidad_material` INT NULL,
  PRIMARY KEY (`fk_tratamiento_id`, `fk_paciente_id`),
  INDEX `fk_paciente_id_idx` (`fk_paciente_id` ASC) VISIBLE,
  INDEX `cantidad_material_idx` (`cantidad_material` ASC) VISIBLE,
  CONSTRAINT `fk_tratamiento_id`
    FOREIGN KEY (`fk_tratamiento_id`)
    REFERENCES `clinica_dental`.`Tratamiento` (`idTratamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_id`
    FOREIGN KEY (`fk_paciente_id`)
    REFERENCES `clinica_dental`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cantidad_material`
    FOREIGN KEY (`cantidad_material`)
    REFERENCES `clinica_dental`.`Material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_dental`.`Tratamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_dental`.`Tratamiento` (
  `idTratamiento` INT NOT NULL AUTO_INCREMENT,
  `detalle` VARCHAR(45) NOT NULL,
  `cantidad_citas` INT NULL,
  `precio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTratamiento`),
  CONSTRAINT `fk_dentista_id`
    FOREIGN KEY (`idTratamiento`)
    REFERENCES `clinica_dental`.`Dentista` (`idDentista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
